import 'dart:math' as math;

import 'package:flutter/material.dart';

import 'colors.dart';
import 'neumorphic.dart';

/// A complete themeable colour identity: light scheme, dark scheme, the
/// neumorphic shadow pair for each, and the mascot's own colours.
///
/// The app ships several of these and lets you pick one (Settings ›
/// Appearance), because "cozy" is not a universal fact — the terracotta-on-oat
/// original reads as warm to some people and as *brown* to others, and there
/// is no argument to be had about that. Changing the palette changes the
/// ground as well as the accent, which is the only way an app actually stops
/// looking like the colour you didn't want.
///
/// [warmPaper] is a literal, hand-tuned scheme. Every other palette is
/// generated by [Palette.fromSeed], which re-uses warm paper's own HSL
/// structure — the same lightness ladder, the same saturation falloff across
/// the surface roles, the same hue offsets between primary, secondary and the
/// neutrals — at a different base hue. That is why a generated palette holds
/// together instead of looking like a hue-rotated screenshot.
@immutable
class Palette {
  const Palette({
    required this.id,
    required this.seedHue,
    required this.light,
    required this.dark,
    required this.neumorphicLight,
    required this.neumorphicDark,
    required this.mascot,
  });

  /// Stable key written to shared_preferences. Never localise this.
  final String id;

  /// The base hue the palette is built around, in degrees. Kept so a custom
  /// palette can be round-tripped through prefs, and so the settings swatches
  /// can be ordered around the wheel.
  final double seedHue;

  final ColorScheme light;
  final ColorScheme dark;
  final NeumorphicTheme neumorphicLight;
  final NeumorphicTheme neumorphicDark;
  final MascotPalette mascot;

  ColorScheme scheme(Brightness brightness) =>
      brightness == Brightness.dark ? dark : light;

  NeumorphicTheme neumorphic(Brightness brightness) =>
      brightness == Brightness.dark ? neumorphicDark : neumorphicLight;

  /// Prefix marking a generated palette in prefs, e.g. `custom:268`.
  static const customPrefix = 'custom:';

  static const customId = 'custom';

  bool get isCustom => id.startsWith(customPrefix) || id == customId;

  /// The id to persist. Generated palettes carry their hue so they survive a
  /// restart; built-ins are just their name.
  String get storageId =>
      isCustom ? '$customPrefix${seedHue.round()}' : id;

  // -------------------------------------------------------------------
  // Built-ins
  // -------------------------------------------------------------------

  /// The original hand-tuned scheme. Its literals live in [AppColors] and are
  /// **not** generated, so the palette the app was designed against survives
  /// exactly, to the byte, no matter how the recipe below evolves.
  static const warmPaper = Palette(
    id: 'warm_paper',
    seedHue: 16,
    light: AppColors.light,
    dark: AppColors.dark,
    neumorphicLight: NeumorphicTheme(
      shadowColor: AppColors.neumorphicShadow,
      highlightColor: AppColors.neumorphicHighlight,
      surfaceColor: AppColors.surface,
    ),
    neumorphicDark: NeumorphicTheme(
      shadowColor: AppColors.neumorphicShadowDark,
      highlightColor: AppColors.neumorphicHighlightDark,
      surfaceColor: AppColors.darkSurface,
    ),
    mascot: MascotPalette(
      body: AppColors.mascotBody,
      ink: AppColors.mascotInk,
      blush: AppColors.mascotBlush,
    ),
  );

  /// Hues chosen to be clearly distinguishable from one another rather than
  /// evenly spaced: adjacent hues that read as "two slightly different blues"
  /// are a worse menu than four obviously different moods.
  static final inkIris = Palette.fromSeed(id: 'ink_iris', hue: 262);
  static final seaGlass = Palette.fromSeed(id: 'sea_glass', hue: 178);
  static final plum = Palette.fromSeed(id: 'plum', hue: 328);
  static final slate = Palette.fromSeed(
    id: 'slate',
    hue: 212,
    // Slate is the quiet one: the accent holds its colour but the paper is
    // nearly neutral, for anyone who wants no tint on the page at all.
    neutralChroma: 0.35,
  );
  static final moss = Palette.fromSeed(id: 'moss', hue: 122);

  static final builtIns = <Palette>[
    warmPaper,
    inkIris,
    seaGlass,
    plum,
    slate,
    moss,
  ];

  /// Resolves a persisted [storageId] back to a palette, falling back to
  /// [warmPaper] for anything unrecognised — a prefs value written by a newer
  /// build must never leave the app unthemed.
  static Palette fromStorageId(String? id) {
    if (id == null) return warmPaper;
    if (id.startsWith(customPrefix)) {
      final hue = double.tryParse(id.substring(customPrefix.length));
      if (hue == null) return warmPaper;
      return Palette.fromSeed(id: customId, hue: hue);
    }
    return builtIns.firstWhere(
      (palette) => palette.id == id,
      orElse: () => warmPaper,
    );
  }

  // -------------------------------------------------------------------
  // The recipe
  // -------------------------------------------------------------------

  /// Builds a full palette around [hue] (degrees) using warm paper's measured
  /// HSL structure.
  ///
  /// Rotating a hue is not enough on its own: at a fixed HSL lightness, yellow
  /// is far brighter than blue, so a naive rotation silently drops text
  /// contrast below AA on some parts of the wheel. Every foreground role below
  /// is therefore pushed until it *measures* as compliant against the surface
  /// it actually sits on — see [_meet] — and the `on` colours are chosen by
  /// measurement rather than assumed to be white. `palette_test.dart` asserts
  /// this holds for every built-in and for the whole wheel in 10° steps.
  ///
  /// [neutralChroma] scales how strongly the greys are tinted toward the hue;
  /// [accentChroma] does the same for the coloured roles. Both default to warm
  /// paper's own values.
  factory Palette.fromSeed({
    required String id,
    required double hue,
    double neutralChroma = 1,
    double accentChroma = 1,
  }) {
    final h = hue % 360;
    Color a(double dh, double s, double l, double chroma) =>
        HSLColor.fromAHSL(
          1,
          (h + dh) % 360,
          (s * chroma / 100).clamp(0.0, 1.0),
          (l / 100).clamp(0.0, 1.0),
        ).toColor();

    Color accent(double dh, double s, double l) => a(dh, s, l, accentChroma);
    Color neutral(double dh, double s, double l) => a(dh, s, l, neutralChroma);

    // ---- light ----
    final surface = neutral(20.7, 41.9, 93.9);
    final lowest = neutral(23.8, 100, 98.2);
    final inkLight = neutral(13.8, 15, 15.7);

    final primary = _meet(accent(0, 56.5, 42.4), surface, 4.5, darken: true);
    final secondary = _meet(
      accent(121.6, 21.4, 33.9),
      surface,
      4.5,
      darken: true,
    );
    final tertiary = _meet(accent(18.5, 70.4, 31.8), surface, 4.5, darken: true);
    final onSurfaceVariant = _meet(
      neutral(15.3, 12.3, 30.4),
      surface,
      4.5,
      darken: true,
    );
    final outline = _meet(neutral(15, 11.2, 43.7), surface, 3, darken: true);

    final lightScheme = ColorScheme(
      brightness: Brightness.light,
      primary: primary,
      onPrimary: _on(primary, inkLight),
      primaryContainer: accent(3.8, 68.4, 88.8),
      onPrimaryContainer: _meet(
        accent(-0.3, 69.6, 18),
        accent(3.8, 68.4, 88.8),
        4.5,
        darken: true,
      ),
      secondary: secondary,
      onSecondary: _on(secondary, inkLight),
      secondaryContainer: accent(112.3, 31.3, 86.9),
      onSecondaryContainer: _meet(
        accent(121.5, 33.3, 15.9),
        accent(112.3, 31.3, 86.9),
        4.5,
        darken: true,
      ),
      tertiary: tertiary,
      onTertiary: _on(tertiary, inkLight),
      tertiaryContainer: accent(23.4, 77.8, 85.9),
      onTertiaryContainer: _meet(
        accent(20.2, 83.6, 14.3),
        accent(23.4, 77.8, 85.9),
        4.5,
        darken: true,
      ),
      // Error keeps its own hue in every palette. It is a semantic colour, not
      // an accent — a red that drifts to match the theme stops reading as an
      // alarm, and this is the one role where recognition beats harmony.
      error: AppColors.error,
      onError: AppColors.onError,
      errorContainer: AppColors.errorContainer,
      onErrorContainer: AppColors.onErrorContainer,
      surface: surface,
      onSurface: inkLight,
      onSurfaceVariant: onSurfaceVariant,
      surfaceContainerLowest: lowest,
      surfaceContainerLow: neutral(19.1, 39.5, 91.6),
      surfaceContainer: neutral(19.8, 35.7, 89),
      surfaceContainerHigh: neutral(20.3, 32.4, 86.1),
      surfaceContainerHighest: neutral(19.3, 31, 82.9),
      surfaceDim: neutral(18.6, 30.7, 80.2),
      surfaceBright: lowest,
      outline: outline,
      outlineVariant: neutral(18.1, 25, 78),
      inverseSurface: neutral(13.8, 13.7, 20),
      onInverseSurface: neutral(18.1, 38.9, 92.9),
      inversePrimary: accent(-0.2, 100, 80.2),
    );

    // ---- dark ----
    final darkSurface = neutral(9.5, 14.3, 9.6);
    final inkDark = neutral(16.8, 35.7, 89);

    final darkPrimary = _meet(
      accent(1.5, 78.3, 72.9),
      darkSurface,
      4.5,
      darken: false,
    );
    final darkSecondary = _meet(
      accent(112.6, 26.1, 69.2),
      darkSurface,
      4.5,
      darken: false,
    );
    final darkTertiary = _meet(
      accent(20.8, 69, 69.6),
      darkSurface,
      4.5,
      darken: false,
    );
    final darkOnSurfaceVariant = _meet(
      neutral(14.9, 22, 75.9),
      darkSurface,
      4.5,
      darken: false,
    );
    final darkOutline = _meet(
      neutral(14.9, 11.7, 54.7),
      darkSurface,
      3,
      darken: false,
    );
    final darkPrimaryContainer = accent(1.5, 63, 25.4);
    final darkSecondaryContainer = accent(112.6, 26, 23);
    final darkTertiaryContainer = accent(20.8, 75, 21);

    final darkScheme = ColorScheme(
      brightness: Brightness.dark,
      primary: darkPrimary,
      onPrimary: _on(darkPrimary, neutral(9.5, 31.8, 12)),
      primaryContainer: darkPrimaryContainer,
      onPrimaryContainer: _meet(
        accent(3.8, 100, 90),
        darkPrimaryContainer,
        4.5,
        darken: false,
      ),
      secondary: darkSecondary,
      onSecondary: _on(darkSecondary, neutral(9.5, 31.8, 12)),
      secondaryContainer: darkSecondaryContainer,
      onSecondaryContainer: _meet(
        accent(112.3, 31.3, 86.9),
        darkSecondaryContainer,
        4.5,
        darken: false,
      ),
      tertiary: darkTertiary,
      onTertiary: _on(darkTertiary, neutral(9.5, 31.8, 12)),
      tertiaryContainer: darkTertiaryContainer,
      onTertiaryContainer: _meet(
        accent(23.4, 77.8, 85.9),
        darkTertiaryContainer,
        4.5,
        darken: false,
      ),
      error: AppColors.dark.error,
      onError: AppColors.dark.onError,
      errorContainer: AppColors.dark.errorContainer,
      onErrorContainer: AppColors.dark.onErrorContainer,
      surface: darkSurface,
      onSurface: inkDark,
      onSurfaceVariant: darkOnSurfaceVariant,
      surfaceContainerLowest: neutral(3.8, 17.6, 6.7),
      surfaceContainerLow: neutral(10.4, 14.3, 12.4),
      surfaceContainer: neutral(7.8, 13.9, 14.1),
      surfaceContainerHigh: neutral(8.8, 13, 18),
      surfaceContainerHighest: neutral(8.8, 10.5, 22.4),
      surfaceDim: darkSurface,
      surfaceBright: neutral(8.8, 10.5, 24),
      outline: darkOutline,
      outlineVariant: neutral(13.8, 11.6, 27.1),
      inverseSurface: inkDark,
      onInverseSurface: neutral(13.8, 13.7, 18),
      inversePrimary: primary,
    );

    // The pet keeps one set of colours across both themes, so its body has to
    // clear the *dark* ground while its ink clears its own body.
    final body = _meet(accent(7, 53, 60.8), darkSurface, 3, darken: false);
    final mascotInk = _meet(neutral(9.5, 31.8, 17.3), body, 4.5, darken: true);

    return Palette(
      id: id,
      seedHue: h,
      light: lightScheme,
      dark: darkScheme,
      neumorphicLight: NeumorphicTheme(
        shadowColor: neutral(18.1, 30.4, 82),
        highlightColor: neutral(26.6, 100, 98.6),
        surfaceColor: surface,
      ),
      neumorphicDark: NeumorphicTheme(
        shadowColor: neutral(7.8, 18.5, 5.3),
        highlightColor: neutral(11, 13.6, 15.9),
        surfaceColor: darkSurface,
      ),
      mascot: MascotPalette(
        body: body,
        ink: mascotInk,
        blush: accent(-3, 51.3, 46.7),
      ),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Palette && other.storageId == storageId;

  @override
  int get hashCode => storageId.hashCode;
}

/// The mascot's colours, carried on the theme so [MascotSlot] never imports a
/// palette directly and follows whatever the user picked.
@immutable
class MascotPalette extends ThemeExtension<MascotPalette> {
  const MascotPalette({
    required this.body,
    required this.ink,
    required this.blush,
  });

  final Color body;
  final Color ink;
  final Color blush;

  /// Shaded toward the pet's own ink rather than toward a surface role, so the
  /// light always falls the same way on it whichever theme it stands in.
  Color get bodyShade => Color.lerp(body, ink, 0.2)!;

  @override
  MascotPalette copyWith({Color? body, Color? ink, Color? blush}) =>
      MascotPalette(
        body: body ?? this.body,
        ink: ink ?? this.ink,
        blush: blush ?? this.blush,
      );

  @override
  MascotPalette lerp(MascotPalette? other, double t) {
    if (other == null) return this;
    return MascotPalette(
      body: Color.lerp(body, other.body, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      blush: Color.lerp(blush, other.blush, t)!,
    );
  }
}

/// WCAG relative-contrast ratio between two opaque colours.
double contrastRatio(Color a, Color b) {
  final la = a.computeLuminance();
  final lb = b.computeLuminance();
  final hi = math.max(la, lb);
  final lo = math.min(la, lb);
  return (hi + 0.05) / (lo + 0.05);
}

/// Picks whichever of white or [ink] is more legible on [background].
///
/// Assuming white is what breaks hue-rotated palettes: white on a yellow or
/// lime accent is around 2:1, and the button label disappears.
Color _on(Color background, Color ink) =>
    contrastRatio(Colors.white, background) >= contrastRatio(ink, background)
    ? Colors.white
    : ink;

/// Walks [foreground]'s lightness until it clears [min] against [background].
///
/// Steps of 1% keep the shift invisible where it isn't needed and bounded
/// where it is; if the colour runs out of headroom before it passes, the
/// closest attempt is returned rather than something arbitrary, and the
/// palette test is what catches that case.
Color _meet(
  Color foreground,
  Color background,
  double min, {
  required bool darken,
}) {
  var hsl = HSLColor.fromColor(foreground);
  var best = foreground;
  var bestRatio = contrastRatio(foreground, background);
  for (var i = 0; i < 100 && bestRatio < min; i++) {
    final lightness = (hsl.lightness + (darken ? -0.01 : 0.01)).clamp(0.0, 1.0);
    if (lightness == hsl.lightness) break;
    hsl = hsl.withLightness(lightness);
    final candidate = hsl.toColor();
    final ratio = contrastRatio(candidate, background);
    if (ratio > bestRatio) {
      bestRatio = ratio;
      best = candidate;
    }
  }
  return best;
}
